services:
  # app:
  #   build: .
  #   container_name: college_store_app
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     - MONGO_URL=mongodb://mongo:27017
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - .:/app
  #   networks:
  #     - college_store_network

  mongo:
    image: mongo:latest
    container_name: college_store_mongo
    ports:
      - "27017:27017"
    networks:
      - college_store_network
    volumes:
      - mongo_data:/data/db

  migrate:
    build: .
    environment:
      - MONGO_URL=mongodb://mongo:27017
    command: node run-migrations.js
    depends_on:
      - mongo
    networks:
      - college_store_network
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data 
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  college_store_network:
    driver: bridge

volumes:
  mongo_data:
  redis_data:
    driver: local
