services:
  mongo:
    image: mongo:latest
    container_name: college_store_mongo
    ports:
      - "27017:27017"
    networks:
      - college_store_network
    volumes:
      - mongo_data:/data/db

  migrate:
    build: .
    environment:
      - MONGO_URL=mongodb://mongo:27017
    command: node run-migrations.js
    depends_on:
      - mongo
      - consul
    networks:
      - college_store_network

  consul:
    image: hashicorp/consul:latest
    container_name: college_store_consul
    networks:
      - college_store_network
    ports:
      - "8500:8500"        
      - "8600:8600/udp"
    command: agent -dev -client=0.0.0.0
    volumes:
      - consul_data:/consul/data

networks:
  college_store_network:
    driver: bridge

volumes:
  mongo_data:
  consul_data:
